### ISSUE TITLE
Document the poison byte value choice

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#123]
isocalloc's poison byte is defined as `0xde`, while it's `0x00` in hardened_malloc.
It would be nice to document the choice of this particular constant :)

**Comment by struct** [comment]
I've been asked this before actually. Theres no particular reason it's 0xde and not another non-zero value. A 0x0 byte probably masks some bugs. It's documented as `SANITIZE_CHUNKS` in the README.
