### ISSUE TITLE
Special handling for zero-sized allocations

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#16]
For zero-sized allocations, [hardened_malloc](https://github.com/GrapheneOS/hardened_malloc) does the following:

> Zero size allocations are a dedicated size class with the entire region remaining non-readable and non-writable.

This guarantees that the application can't use the allocation in any way. Currently, isoalloc puts 0-sized allocations in the zone for the smallest possible objects instead.

**Comment by struct** [comment]
I took a shot at implementing this here https://github.com/struct/isoalloc/pull/20 - Feedback welcome!
