### ISSUE TITLE
Implement posix_memalign correctly

### ISSUE THREAD

**Issue by htfy96** [struct/isoalloc#204]
**Is your feature request related to a problem? Please describe.**
Currently in malloc_hook.c, all aligned allocation requests were forwarded to plain `iso_alloc`, which leads to incorrect result when the alignment is larger than 8 bytes.

**Describe the solution you'd like**
Return aligned memory chunks correctly

**Describe alternatives you've considered**
Change the call sites to over allocate and manually align, but it's always a pain to keep track of the original pointer.

**Additional context**
N/A

**Comment by struct** [comment]
The choice to pass calls to `posix_memalign` to `iso_alloc` is deliberate. But you are correct, as a result allocations will be 8 byte aligned. I think the easiest way to solve this is to just check if alignment value is greater than size and if it is just set size to the alignment value.
