### ISSUE TITLE
GCC port

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#28]
I'm currently trying to port isoalloc to gcc, and I'm facing a couple of issues on which I would like some input:

```C
src/iso_alloc.c: In function ‘create_guard_page’:
src/iso_alloc.c:260:58: error: ISO C99 requires at least one argument for the "..." in a variadic macro [-Werror]
  260 |             LOG_AND_ABORT("Could not allocate guard page");
      |                                                          ^
```

Do we want to have a `LOG_AND_ABORT_FMT` and a `LOG_AND_ABORT` macro to fix this?

---

```C
src/iso_alloc.c:1345:32: error: ‘always_inline’ function might not be inlinable [-Werror=attributes]
 1345 | INTERNAL_HIDDEN INLINE int64_t check_canary_no_abort(iso_alloc_zone *zone, void *p) {
```

it seems that gcc isn't a huge fan of the way inlining is specified. Replacing `#define INLINE __attribute__((always_inline))` with `#define INLINE __attribute__((always_inline)) inline` "fixes" the issue, but yields a ton of new ones.

---

```C
src/iso_alloc_printf.c: In function ‘_iso_alloc_printf’:
src/iso_alloc_printf.c:123:5: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  123 |     write(fd, out, strlen(out));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Shall we change `_iso_alloc_printf` to return an error, or simply call `abort()` in case of a failure?

--- 

```C
In file included from /usr/include/string.h:519,
                 from src/iso_alloc_printf.c:8:
In function ‘strncpy’,
    inlined from ‘_iso_alloc_printf’ at src/iso_alloc_printf.c:118:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:10: error: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |       __glibc_objsize (__dest));
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~
src/iso_alloc_printf.c: In function ‘_iso_alloc_printf’:
src/iso_alloc_printf.c:118:13: note: length computed here
  118 |             strncpy(p, s, strlen(s));
```

This is a fun one: gcc isn't smart enough to understand that this is safe. I don't see an elegant way to please it.

**Comment by struct** [comment]
> Do we want to have a LOG_AND_ABORT_FMT and a LOG_AND_ABORT macro to fix this?
> This is a fun one: gcc isn't smart enough to understand that this is safe. I don't see an elegant way to please it.
> it seems that gcc isn't a huge fan of the way inlining is specified. Replacing #define INLINE __attribute__((always_inline)) with #define INLINE __attribute__((always_inline)) inline "fixes" the issue, but yields a ton of new ones.

If you conditionally turn off `-pedantic` and `-Werror` for GCC you may be able to make progress on these. Im not sure how I want to proceed with them just yet. Inlining matters for performance in specific hot paths, but I'm less concerned about variadic macros in debug builds. I'll have to experiment with `FORTIFY` because in most cases I don't want it in the allocator itself.

> Shall we change _iso_alloc_printf to return an error, or simply call abort() in case of a failure?

I think return an error but it's almost always going to be ignored, its all debug code.

**Comment by jvoisin** [comment]
Last one:

```C
src/iso_alloc_profiler.c: In function ‘_iso_alloc_zone_leak_detector’:
include/iso_alloc_internal.h:518:32: error: inlining failed in call to ‘always_inline’ ‘check_canary_no_abort’: function body not available
  518 | INTERNAL_HIDDEN INLINE int64_t check_canary_no_abort(iso_alloc_zone *zone, void *p);
      |                                ^~~~~~~~~~~~~~~~~~~~~
src/iso_alloc_profiler.c:103:37: note: called from here
  103 |                 if(bit_two == 1 && (check_canary_no_abort(zone, leak) != ERR)) {
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Because `check_canary_no_abort` is declared in `include/iso_alloc_internal.h`, but defined in `src/iso_alloc.c`, and `src/iso_alloc_profiler.c` doesn't have access to it. The solution would be to define `check_canary_no_abort` in `include/iso_alloc_internal.h`, but it looks a bit gross to me.

What do you think?

**Comment by struct** [comment]
The profiler is the only code that calls `check_canary_no_abort` so for now lets just remove the inline attribute from `check_canary_no_abort` and unblock gcc support. Long term it probably makes sense to make a header just for inline functions. Isoalloc over uses the attribute today so I will have to reevaluate which functions truly need it.
