### ISSUE TITLE
Minor Typo in README

### ISSUE THREAD

**Issue by maxbla** [struct/isoalloc#3]
`void iso_verify_zone(iso_alloc_zone_handle *zone - Verifies the state of specified zone. Will abort if inconsistencies are found.`
Is missing a close paren and should read
`void iso_verify_zone(iso_alloc_zone_handle *zone) - Verifies the state of specified zone. Will abort if inconsistencies are found.`

**Comment by struct** [comment]
Thanks, fixed!
