### ISSUE TITLE
Add compiler annotations to allocation functions

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#40]
It would be great to add compiler annotations like [`alloc_size`]( https://clang.llvm.org/docs/AttributeReference.html#alloc-size ), [`malloc`]( https://clang.llvm.org/docs/AttributeReference.html#malloc ), …

**Comment by jvoisin** [comment]
Unfortunately, it seems that some of them are wrong:

- the `malloc` attribute specifies that a function can't return pointers pointing to the same address, which can happen when `NO_ZERO_ALLOCATIONS` is enabled.
- the `malloc` attribute specifies that a function returns uninitialized memory, which isn't the case for `calloc` and `realloc`.

**Comment by struct** [comment]
> the malloc attribute specifies that a function can't return pointers pointing to the same address, which can happen when NO_ZERO_ALLOCATIONS is enabled.

This is true but NO_ZERO_ALLOCATIONS is enabled by default. Im not sure how I want to proceed here just yet.

> the malloc attribute specifies that a function returns uninitialized memory, which isn't the case for calloc and realloc.

I was following [Clang 13 documentation](https://clang.llvm.org/docs/AttributeReference.html#malloc) for this attribute. GCC [documentation](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) states:

> Functions like malloc and calloc have this property because they return a pointer to uninitialized or zeroed-out, newly obtained storage. However, functions like realloc do not have this property.

I think it's safe and a good idea to remove this attribute from `realloc`

**Comment by jvoisin** [comment]
No idea about the `NO_ZERO_ALLOCATIONS`, hence why I commented here instead of sending a patch :D
