### ISSUE TITLE
Unespected `abort` when running the espresso benchmark

### ISSUE THREAD

**Issue by jvoisin** [struct/isoalloc#56]
As part of my effort to benchmark memory allocators in [mimalloc-bench](https://github.com/daanx/mimalloc-bench), I've stumbled upon the following `abort` in isoalloc when running the espresso bench:

```
$ LD_PRELOAD=/home/jvoisin/dev/mimalloc-bench/extern/iso/build/libisoalloc.so ./espresso ../../bench/espresso/largest.espresso
[ABORTING][373144](src/iso_alloc.c:1757 _iso_chunk_size()) Could not find any zone for allocation at 0x347ae209e000
Aborted
```

Is this working as intended? Every other memory allocator (even hardened ones) are handling this benchmark without crashing.

**Comment by struct** [comment]
Fixed in https://github.com/struct/isoalloc/pull/58
